import { Inter } from "next/font/google";
import "./globals.css";
import { Web3Modal } from "@/context/web3modal";
import { CustomProvider } from 'rsuite';
import 'rsuite/dist/rsuite-no-reset.min.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Athena",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Web3Modal>
          <CustomProvider>
            {children}
          </CustomProvider>
        </Web3Modal>
        </body>
    </html>
  );
}
